// Model-specific board records. Loaded after data.js and before the main app script.
if(typeof electroGuideDetails!=="undefined"&&electroGuideDetails["esp32"]){
  const e=electroGuideDetails["esp32"];
  e.name="ESP32 DevKit / ESP32-WROOM Development Board";
  e.description="A Wi-Fi and Bluetooth-enabled 32-bit microcontroller development platform used for IoT, robotics, automation and embedded projects.";
  e.image="https://commons.wikimedia.org/wiki/Special:FilePath/ESP32%20Espressif%20ESP-WROOM-32%20Dev%20Board.jpg";
  e.facts=[["Core","ESP32 series SoC"],["Wireless","Wi-Fi + Bluetooth"],["CPU","32-bit Xtensa"],["Clock","Up to 240 MHz on classic ESP32"],["Flash","Board/module dependent"],["Logic","3.3 V"],["ADC","12-bit"],["DAC","2 channels"]];
  e.sections={"What is ESP32?":"ESP32 is a family of low-cost, low-power microcontroller SoCs from Espressif with integrated Wi-Fi and Bluetooth. ESP32 development boards expose the SoC's GPIO and peripherals for rapid prototyping.","How it Works":"Firmware runs on the ESP32 CPU and controls GPIO and integrated peripherals. The wireless subsystem handles Wi-Fi/Bluetooth communication while ADC, DAC, PWM, SPI, I2C, UART and other peripherals interface with external hardware.","Why is it Used?":"It combines substantial processing capability with wireless connectivity, making it especially useful for IoT and connected embedded systems.","Where is it Used?":"IoT devices, smart-home systems, robotics, wireless sensors, automation, data logging and connected instrumentation.","Applications":"Wi-Fi sensor nodes, web-controlled devices, Bluetooth projects, MQTT/IoT systems, smart appliances, robotics and wireless data acquisition.","Advantages":"Integrated wireless connectivity, many peripherals, strong processing capability and a large embedded-development ecosystem.","Disadvantages":"3.3 V logic requires care with 5 V peripherals, and exact memory/pin features vary between ESP32 variants and development boards.","Precautions":"Use the exact board/module datasheet for power, GPIO and RF requirements. Do not assume every ESP32 board has the same USB interface, flash size or pinout."};
}
