// ElectroGuide component knowledge base.
// Every library item gets a complete learning record through the category-aware generator.

const electroGuideDetails = {
  "arduino-uno": {
    name:"Arduino Uno R3", category:"Microcontrollers",
    description:"A beginner-friendly development board based on the ATmega328P for embedded systems, sensors, automation and robotics.",
    image:"https://upload.wikimedia.org/wikipedia/commons/3/38/Arduino_Uno_-_R3.jpg",
    facts:[["MCU","ATmega328P"],["Logic","5 V"],["Digital I/O","14"],["Analog inputs","6"],["PWM","6"],["Clock","16 MHz"],["Flash","32 KB"],["SRAM","2 KB"],["EEPROM","1 KB"]],
    sections:{"What is Arduino Uno?":"Arduino Uno R3 is a development board built around the ATmega328P. It combines the MCU with USB programming, power, clock, reset and accessible I/O headers.","How it Works":"A program is transferred through USB and executed by the ATmega328P. The MCU reads inputs and sensors, processes data and drives outputs such as LEDs, displays, drivers and motors.","Why is it Used?":"It is easy to program, inexpensive and supported by many libraries, sensors, modules and tutorials. It is excellent for learning GPIO, ADC, PWM and serial communication.","Where is it Used?":"ECE laboratories, robotics, automation, sensor monitoring, control prototypes and embedded-system education.","Applications":"LED control, temperature monitoring, obstacle detection, servo control, LCD projects, Bluetooth projects and data logging.","Advantages":"Simple programming, large ecosystem, accessible I/O and strong educational support.","Disadvantages":"Limited memory and processing compared with modern 32-bit boards; 5 V logic is not suitable for every low-voltage peripheral.","Precautions":"Use correct supply voltage and stay within the electrical and thermal limits of the board and I/O pins."},
    internalComponents:[
      {id:"atmega328p",name:"ATmega328P",description:"Main 8-bit AVR microcontroller that executes the program and provides GPIO, timers, ADC and serial interfaces."},
      {id:"atmega16u2",name:"ATmega16U2 USB Interface",description:"Handles USB communication between the computer and the Uno's serial interface."},
      {id:"16mhz-resonator",name:"16 MHz Clock Resonator",description:"Provides the timing reference used by the main microcontroller."},
      {id:"5v-regulator",name:"5 V Voltage Regulator",description:"Provides the regulated 5 V power rail from an appropriate external input."},
      {id:"3v3-regulator",name:"3.3 V Regulator",description:"Provides the board's 3.3 V rail for compatible peripherals."},
      {id:"reset-circuit",name:"Reset Circuit",description:"Supports manual and automatic reset of the ATmega328P."},
      {id:"usb-connector",name:"USB Connector",description:"Connects the Uno to a computer for programming, serial communication and USB power."},
      {id:"dc-jack",name:"DC Barrel Jack",description:"Accepts an external DC power source through the board's power input."},
      {id:"polyfuse",name:"USB Polyfuse",description:"Resettable overcurrent protection component on the USB power path."},
      {id:"power-led",name:"Power LED",description:"Visual indicator showing that board power is present."},
      {id:"tx-rx-leds",name:"TX/RX LEDs",description:"Visual indicators associated with serial data activity."},
      {id:"passive-components",name:"Resistors & Capacitors",description:"Support filtering, biasing, timing and supply decoupling around the active devices."},
      {id:"headers",name:"Pin Headers",description:"Expose power, analog, digital and communication signals for external circuits."}
    ]
  }
};

const electroGuideInternalDetails = {
  "atmega328p":{name:"ATmega328P",category:"Arduino Uno Internal Component",description:"The main 8-bit AVR MCU used by the Uno R3.",facts:[["Architecture","8-bit AVR"],["Clock","16 MHz on Uno"],["Flash","32 KB"],["SRAM","2 KB"],["EEPROM","1 KB"],["ADC","10-bit"]],sections:{"How it Works":"The CPU executes firmware from flash and uses GPIO, timers, ADC and serial peripherals to interact with the circuit.","Why is it Used?":"It combines processing, memory and common embedded peripherals in one device.","Where is it Used?":"Arduino Uno and small embedded-control projects."}},
  "atmega16u2":{name:"ATmega16U2 USB Interface",category:"Arduino Uno Internal Component",description:"USB interface MCU used on the Uno R3.",facts:[["Type","USB-capable AVR"],["Role","USB-to-serial"]],sections:{"How it Works":"It handles USB communication and presents serial data to the main MCU.","Why is it Used?":"It enables convenient USB programming and serial communication."}},
  "16mhz-resonator":{name:"16 MHz Clock Resonator",category:"Arduino Uno Internal Component",description:"Clock reference for the Uno's main MCU.",facts:[["Frequency","16 MHz"],["Role","Clock source"]],sections:{"How it Works":"It provides the timing reference for CPU and peripheral operation.","Why is it Used?":"Accurate timing is required for firmware execution and communication."}},
  "5v-regulator":{name:"5 V Voltage Regulator",category:"Arduino Uno Internal Component",description:"Regulated 5 V supply section of the Uno.",facts:[["Output","5 V"],["Role","Power regulation"]],sections:{"How it Works":"It regulates suitable external input power to the board's 5 V rail.","Why is it Used?":"The MCU and many peripherals require a stable supply."}},
  "3v3-regulator":{name:"3.3 V Regulator",category:"Arduino Uno Internal Component",description:"Provides a regulated 3.3 V rail for compatible peripherals.",facts:[["Output","3.3 V"],["Role","Low-voltage supply"]],sections:{"How it Works":"It converts available input power into the lower regulated rail.","Why is it Used?":"Some modules require 3.3 V rather than 5 V."}},
  "reset-circuit":{name:"Reset Circuit",category:"Arduino Uno Internal Component",description:"Supporting circuit for restarting the ATmega328P.",facts:[["Role","MCU reset"],["Control","Reset button + auto reset"]],sections:{"How it Works":"A reset signal places the MCU in reset and then allows normal program execution.","Why is it Used?":"It provides reliable restarting and supports programming."}},
  "usb-connector":{name:"USB Connector",category:"Arduino Uno Internal Component",description:"Physical USB connection for programming, communication and power.",facts:[["Interface","USB"],["Role","PC connection"]],sections:{"How it Works":"A USB cable links the computer with the board's USB interface.","Why is it Used?":"It makes firmware upload and serial monitoring convenient."}},
  "dc-jack":{name:"DC Barrel Jack",category:"Arduino Uno Internal Component",description:"External DC power connector.",facts:[["Type","Barrel connector"],["Role","External power"]],sections:{"How it Works":"An appropriate DC source enters the board through the power-input path.","Why is it Used?":"It powers the board without relying on USB."}},
  "polyfuse":{name:"USB Polyfuse",category:"Arduino Uno Internal Component",description:"Resettable overcurrent protection device on the USB power path.",facts:[["Type","Resettable fuse"],["Role","USB protection"]],sections:{"How it Works":"Excess current heats the device and increases its resistance; after the fault is removed it can recover.","Why is it Used?":"It helps protect the USB power path from excessive current."}},
  "power-led":{name:"Power LED",category:"Arduino Uno Internal Component",description:"LED that indicates board power is present.",facts:[["Type","LED"],["Role","Power indication"]],sections:{"Why is it Used?":"It gives a quick visual confirmation that the board is powered."}},
  "tx-rx-leds":{name:"TX/RX LEDs",category:"Arduino Uno Internal Component",description:"LED indicators associated with serial transmit and receive activity.",facts:[["Indicators","TX and RX"],["Role","Serial status"]],sections:{"Why is it Used?":"They provide a visual indication of serial communication activity."}},
  "passive-components":{name:"Resistors & Capacitors",category:"Arduino Uno Internal Component",description:"Supporting passive parts used throughout the board.",facts:[["Types","Resistors + capacitors"],["Role","Support circuitry"]],sections:{"How it Works":"Resistors establish currents and voltage relationships while capacitors filter, decouple and shape signals.","Why is it Used?":"They stabilize power and condition signals around the active devices."}},
  "headers":{name:"Pin Headers",category:"Arduino Uno Internal Component",description:"Connector rows exposing the Uno's signals.",facts:[["Role","External connections"],["Signals","Power + I/O"]],sections:{"Why is it Used?":"They make it easy to connect sensors, displays, drivers and breadboards."}}
};

const electroGuideCategoryKnowledge={
  "Passive Components":{type:"Passive",desc:"A passive electronic component used to control, store, filter or shape electrical energy and signals.",work:"Its electrical property—such as resistance, capacitance or inductance—determines how voltage, current, energy or frequency behaves in a circuit.",apps:"filtering, timing, coupling, biasing, energy storage, protection and signal conditioning",spec:"value, tolerance, voltage/current rating, power rating and frequency behavior",caution:"Choose the correct value and electrical rating; check polarity for polarized parts."},
  "Diodes":{type:"Semiconductor diode",desc:"A semiconductor device whose junction controls current direction or provides optical, protection, regulation or detection functions.",work:"The semiconductor junction has a nonlinear current-voltage characteristic that can be used for rectification, switching, protection, emission or sensing.",apps:"rectification, protection, switching, detection, regulation and optical interfaces",spec:"forward current, reverse voltage, forward drop, power dissipation and switching speed",caution:"Check polarity, reverse-voltage rating, current rating and heat dissipation."},
  "Transistors":{type:"Transistor",desc:"A semiconductor device used to control current for switching, amplification and power conversion.",work:"An input voltage or current controls conduction between the transistor's main terminals.",apps:"switching, amplification, drivers, motor control, digital logic and power conversion",spec:"voltage, current, gain or threshold, switching speed and thermal limits",caution:"Stay within voltage, current, gate/base-drive and thermal limits."},
  "ICs":{type:"Integrated circuit",desc:"A semiconductor device that integrates multiple electronic functions into one compact package.",work:"Internal transistor networks process, amplify, store, convert or control electrical signals according to the IC design.",apps:"timing, logic, conversion, regulation, memory, audio, control and signal processing",spec:"supply voltage, input/output levels, speed, bandwidth, package and absolute maximum ratings",caution:"Follow the correct supply, pinout and timing requirements from the device datasheet."},
  "Sensors":{type:"Sensor",desc:"A device that converts a physical quantity such as light, temperature, pressure, motion or gas concentration into an electrical signal.",work:"A sensing element changes an electrical property in response to a physical condition; signal conditioning converts that change into a useful output.",apps:"measurement, automation, robotics, IoT, safety and environmental monitoring",spec:"range, accuracy, resolution, response time, interface and supply voltage",caution:"Consider calibration, environmental conditions, response time and operating range."},
  "Motors":{type:"Electromechanical actuator",desc:"A device that converts electrical energy into mechanical motion.",work:"Magnetic and electromagnetic forces create torque or linear force on a moving part.",apps:"robotics, fans, pumps, wheels, positioning and automation",spec:"voltage, current, speed, torque, load, duty cycle and thermal limits",caution:"Use an appropriate driver and respect current, voltage and mechanical-load limits."},
  "Power Components":{type:"Power component",desc:"A component or module used to generate, convert, regulate, switch, store or protect electrical power.",work:"It manages energy through conduction, switching, magnetic coupling, chemical storage or regulation.",apps:"power supplies, converters, battery systems, protection and energy distribution",spec:"input/output voltage, current, efficiency, isolation, ripple and thermal limits",caution:"Check polarity, current, voltage, heat, isolation and electrical safety."},
  "Displays":{type:"Display device",desc:"An electronic interface that converts electrical signals into visible information.",work:"Pixels, segments or light-emitting elements are controlled by electrical signals to form numbers, text, graphics or images.",apps:"instrument panels, meters, embedded interfaces, appliances and user interfaces",spec:"interface, resolution, viewing characteristics, supply voltage and current",caution:"Check logic levels, controller interface, current limits and refresh requirements."},
  "Microcontrollers":{type:"Microcontroller/development board",desc:"A programmable embedded controller that executes firmware and interfaces with sensors, actuators and communication devices.",work:"A CPU executes instructions while integrated GPIO, timers, ADC, communication peripherals and memory interact with external hardware.",apps:"embedded control, robotics, IoT, automation, instrumentation and education",spec:"CPU architecture, clock, flash, RAM, GPIO, ADC, PWM, communication and supply voltage",caution:"Check logic levels, pin multiplexing, memory limits, peripheral limits and power requirements."},
  "ECE Project Components":{type:"Project module",desc:"A practical electronics module used to add sensing, communication, actuation or interface functions to ECE projects.",work:"The module combines one or more electronic devices and exposes an easy-to-use electrical interface to a controller.",apps:"robotics, IoT, wireless communication, automation and student projects",spec:"supply voltage, interface type, signal levels, range and current consumption",caution:"Verify module pinout, logic levels, supply requirements and current capability."}
};

function titleFromSlugForData(slug){const special={"hc-sr04":"HC-SR04","hc-05-bluetooth":"HC-05 Bluetooth","hc-06-bluetooth":"HC-06 Bluetooth","mpu6050":"MPU6050","bmp280":"BMP280","mq-2":"MQ-2 Gas Sensor","lm35":"LM35","dht11":"DHT11","dht22":"DHT22","nrf24l01":"NRF24L01","esp32-cam":"ESP32-CAM","stm32-blue-pill":"STM32 Blue Pill","pic16f877a":"PIC16F877A","rp2040":"RP2040","8051":"8051"};return special[slug]||slug.split("-").map(w=>w.charAt(0).toUpperCase()+w.slice(1)).join(" ");}

function hydrateElectroGuideDetails(categories){
  Object.entries(categories).forEach(([key,cat])=>{
    const k=electroGuideCategoryKnowledge[cat.name];
    cat.items.forEach(id=>{
      if(electroGuideDetails[id]||electroGuideInternalDetails[id])return;
      const name=titleFromSlugForData(id);
      electroGuideDetails[id]={name,category:cat.name,description:`${name} is ${k.desc.toLowerCase()}`,image:`https://placehold.co/900x600/0d1b2a/36e0c5?text=${encodeURIComponent(name)}`,facts:[["Type",k.type],["Category",cat.name],["Main Use",k.apps.split(",")[0].trim().replace(/^./,c=>c.toUpperCase())],["Key Specification",k.spec]],sections:{"What is it?":`${name} is ${k.desc}`,"How it Works":k.work,"Why is it Used?":`It is commonly used for ${k.apps}.`,"Where is it Used?":`Typical uses include ${k.apps}.`,"Applications":`Practical applications include ${k.apps}.`,"Advantages":"Compact, practical and widely useful when selected for the correct circuit and operating conditions.","Disadvantages":`Performance depends on correct ratings and operating conditions. ${k.caution}`,"Important Specifications":`Important selection points include ${k.spec}.`,"Precautions":k.caution}};
    });
  });
}
