/* ElectroGuide learning, quiz, games, tools and project engine */
const EG={
 xp(){return Number(localStorage.getItem('eg-xp')||0)}, addXP(n){localStorage.setItem('eg-xp',String(EG.xp()+n));EG.paintStats()},
 streak(){return Number(localStorage.getItem('eg-streak')||0)},
 paintStats(){document.querySelectorAll('[data-xp]').forEach(e=>e.textContent=EG.xp());document.querySelectorAll('[data-level]').forEach(e=>e.textContent=Math.floor(EG.xp()/100)+1);document.querySelectorAll('[data-streak]').forEach(e=>e.textContent=EG.streak())},
 esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
};
const quizBank=[
['Basic Electronics','What is the relationship described by Ohm’s law?',['V = IR','P = VI','Q = CV','f = 1/T'],'V = IR','Voltage, current and resistance are directly related by V = IR.'],
['Basic Electronics','A 10 V source is connected to a 2 kΩ resistor. What current flows?',['2 mA','5 mA','20 mA','50 mA'],'5 mA','I = V/R = 10/2000 = 0.005 A = 5 mA.'],
['Basic Electronics','Which quantity is measured in ohms?',['Voltage','Current','Resistance','Power'],'Resistance','The SI unit of resistance is the ohm (Ω).'],
['Basic Electronics','Which component primarily stores energy in an electric field?',['Inductor','Capacitor','Resistor','Transformer'],'Capacitor','A capacitor stores energy in its electric field.'],
['Basic Electronics','Which component stores energy mainly in a magnetic field?',['Capacitor','Resistor','Inductor','Diode'],'Inductor','An inductor stores energy in its magnetic field.'],
['Basic Electronics','What is electrical power when V = 12 V and I = 2 A?',['6 W','14 W','24 W','48 W'],'24 W','P = VI = 12 × 2 = 24 W.'],
['Components','What is the main purpose of a resistor in a simple LED circuit?',['Limit current','Store magnetic energy','Generate AC','Convert light to voltage'],'Limit current','A series resistor limits LED current and helps protect the LED.'],
['Components','A diode normally conducts easily in which condition?',['Reverse bias','Forward bias','Zero temperature','Open circuit'],'Forward bias','A standard diode conducts when forward biased beyond its practical forward-voltage region.'],
['Components','What is a Zener diode commonly used for?',['Voltage regulation/reference','Mechanical motion','Audio recording','Data storage'],'Voltage regulation/reference','A Zener diode can operate in reverse breakdown to provide voltage regulation or reference behavior.'],
['Components','Which component is commonly used to switch a load electronically?',['Transistor','Fuse','Capacitor','Transformer core'],'Transistor','Transistors are widely used as electronic switches.'],
['Components','What does an LDR respond primarily to?',['Light','Pressure','Humidity','Sound'],'Light','An LDR changes resistance with incident light level.'],
['Components','Which device converts electrical energy into rotational mechanical energy?',['Motor','Photodiode','ADC','Crystal'],'Motor','A motor converts electrical energy into mechanical motion.'],
['Analog Electronics','What is the ideal voltage gain of a voltage follower op-amp circuit?',['0','1','10','Infinite'],'1','A voltage follower has approximately unity voltage gain while providing buffering.'],
['Analog Electronics','What is the main purpose of a rectifier?',['Convert AC to DC','Convert DC to AC','Increase resistance','Store data'],'Convert AC to DC','A rectifier uses diodes to produce a unidirectional output from an AC input.'],
['Analog Electronics','A low-pass filter primarily allows which frequencies to pass?',['Low frequencies','Only high frequencies','Only DC','No frequencies'],'Low frequencies','A low-pass filter attenuates higher frequencies while passing lower frequencies within its passband.'],
['Analog Electronics','What does transistor current gain β represent for a BJT?',['IC/IB','IB/IC','VCE/IC','IE/VBE'],'IC/IB','For a common BJT definition, β is collector current divided by base current.'],
['Analog Electronics','Which circuit converts a changing analog voltage into a digital number?',['ADC','DAC','Oscillator','Relay'],'ADC','An analog-to-digital converter samples an analog quantity and produces a digital representation.'],
['Digital Electronics','Which logic gate outputs 1 only when all inputs are 1?',['OR','AND','XOR','NOT'],'AND','An AND gate is high only when every input is high.'],
['Digital Electronics','Which gate is called an inverter?',['AND','OR','NOT','XOR'],'NOT','A NOT gate produces the logical complement of its input.'],
['Digital Electronics','How many stable states does a basic flip-flop have?',['1','2','3','4'],'2','A basic flip-flop is a bistable circuit with two stable states.'],
['Digital Electronics','What is decimal 10 in binary?',['1010','1001','1100','1110'],'1010','Decimal 10 equals binary 1010.'],
['Digital Electronics','Which circuit selects one of several inputs and forwards the selected one?',['Multiplexer','Counter','Decoder only','Register'],'Multiplexer','A multiplexer selects one input from multiple sources and routes it to its output.'],
['Microcontrollers','Which Arduino Uno MCU is the main application controller?',['ATmega328P','ESP32','STM32F103','RP2040'],'ATmega328P','The Arduino Uno R3 is built around the ATmega328P MCU.'],
['Microcontrollers','Which interface is commonly used for two-wire synchronous peripheral communication?',['I²C','UART','PWM','GPIO only'],'I²C','I²C uses two signal lines: SDA for data and SCL for clock.'],
['Microcontrollers','What does PWM control directly through duty cycle?',['Average delivered power/voltage behavior','Flash size','CPU architecture','USB connector type'],'Average delivered power/voltage behavior','Changing PWM duty cycle changes the average effect of a pulsed signal on suitable loads.'],
['Microcontrollers','Which ESP32 feature is especially useful for IoT projects?',['Wi-Fi and Bluetooth','Vacuum tube amplification','Mechanical relay contacts','CRT display'],'Wi-Fi and Bluetooth','ESP32 development boards commonly provide integrated 2.4 GHz Wi-Fi and Bluetooth capability.'],
['Embedded Systems','What is an interrupt used for?',['Responding to an event without continuous polling','Increasing resistor value','Storing analog energy','Replacing a power supply'],'Responding to an event without continuous polling','An interrupt lets the processor respond to an event through an interrupt service routine.'],
['Embedded Systems','Which protocol is asynchronous and commonly uses TX and RX lines?',['UART','I²C','SPI only','ADC'],'UART','UART commonly communicates asynchronously using transmit and receive signals.'],
['Communication','What is the main purpose of modulation?',['Vary a carrier according to information','Eliminate all noise','Increase resistor power','Store firmware'],'Vary a carrier according to information','Modulation maps information onto a carrier signal for transmission.'],
['Communication','In FM, which carrier property is varied by the message?',['Frequency','Resistance','Capacitance','Physical length'],'Frequency','Frequency modulation varies carrier frequency according to the information signal.'],
['Communication','What does AM vary?',['Carrier amplitude','Carrier resistance','Antenna mass','Battery chemistry'],'Carrier amplitude','Amplitude modulation varies the carrier amplitude with the information signal.'],
['Communication','Which modulation changes carrier phase according to the information?',['PM','AM','FM','PWM'],'PM','Phase modulation varies the carrier phase in response to the message.'],
['Communication','What is sampling frequency required to be at least, ideally, for a band-limited signal with highest frequency B?',['B','2B','B/2','4B only'],'2B','The Nyquist sampling condition requires a sampling frequency greater than twice the highest signal frequency for ideal reconstruction.'],
['Communication','Which unit is commonly used for signal power gain or loss on a logarithmic scale?',['dB','Hz','Ohm','Farad'],'dB','Decibels express ratios such as power gain/loss on a logarithmic scale.'],
['Power Electronics','Which device is commonly used for reverse-polarity or rectification applications?',['Diode','LDR','Microphone','Crystal'],'Diode','Diodes provide controlled current direction and are widely used in rectification and protection.'],
['Power Electronics','Why is a flyback diode placed across a DC relay coil in many circuits?',['To provide a path for inductive transient current','To increase coil voltage','To generate Wi-Fi','To measure temperature'],'To provide a path for inductive transient current','When coil current is interrupted, the diode provides a safer path for the inductive transient.'],
['Measurements','Which instrument measures voltage, current and resistance in common use?',['Multimeter','Oscillator','Antenna','Relay'],'Multimeter','A digital multimeter commonly measures voltage, current and resistance.'],
['Measurements','Which instrument displays voltage versus time for electrical signals?',['Oscilloscope','Transformer','Potentiometer','Fuse'],'Oscilloscope','An oscilloscope displays electrical waveforms, typically voltage versus time.'],
['Safety','What should you check first before connecting a module to a microcontroller?',['Supply voltage and pinout','Its color only','Its package weight','Its logo size'],'Supply voltage and pinout','Correct supply voltage and pinout prevent many wiring and component-damage mistakes.']
];
function initQuiz(){const el=document.getElementById('quiz-app');if(!el)return;let pool=[...quizBank],index=0,score=0,answered=false,selected=[];const cat=document.getElementById('quiz-category'),diff=document.getElementById('quiz-difficulty'),count=document.getElementById('quiz-count'),start=document.getElementById('quiz-start');function begin(){let c=cat.value;pool=(c==='All'?quizBank:quizBank.filter(q=>q[0]===c));pool=pool.sort(()=>Math.random()-.5).slice(0,Math.min(Number(count.value),pool.length));index=0;score=0;answered=false;render()}function render(){if(index>=pool.length){finish();return}const q=pool[index],opts=[...q[2]].sort(()=>Math.random()-.5);el.querySelector('.quiz-progress').textContent=`Question ${index+1} of ${pool.length}`;el.querySelector('.quiz-score').textContent=`Score ${score}`;el.querySelector('.quiz-topic').textContent=q[0]+' • '+diff.value;el.querySelector('.quiz-question').textContent=q[1];const box=el.querySelector('.quiz-options');box.innerHTML=opts.map((o,i)=>`<button class="quiz-option" data-value="${EG.esc(o)}"><span>${String.fromCharCode(65+i)}</span>${EG.esc(o)}</button>`).join('');el.querySelector('.quiz-feedback').textContent='';el.querySelector('.quiz-next').disabled=true;answered=false;box.querySelectorAll('button').forEach(b=>b.onclick=()=>choose(b,opts,q))}function choose(btn,opts,q){if(answered)return;answered=true;const val=btn.dataset.value;const correct=val===q[3];if(correct){score++;EG.addXP(10)}else{EG.addXP(2)}el.querySelectorAll('.quiz-option').forEach(b=>{if(b.dataset.value===q[3])b.classList.add('correct');if(b===btn&&!correct)b.classList.add('wrong');b.disabled=true});el.querySelector('.quiz-feedback').innerHTML=`<strong>${correct?'Correct! +10 XP':'Not quite.'}</strong> ${EG.esc(q[4])}`;el.querySelector('.quiz-next').disabled=false}function next(){if(!answered)return;index++;render()}function finish(){el.querySelector('.quiz-progress').textContent='Quiz complete';el.querySelector('.quiz-question').textContent=`You scored ${score}/${pool.length}`;el.querySelector('.quiz-options').innerHTML=`<div class="result-card"><strong>${Math.round(score/pool.length*100)}%</strong><span>${score>=pool.length*.8?'Excellent work! Keep building your ECE skills.':'Good attempt. Review the weak topics and try again.'}</span></div>`;el.querySelector('.quiz-feedback').textContent=`You earned XP. Start another round for a fresh question order.`;el.querySelector('.quiz-next').disabled=true;document.querySelector('[data-quiz-result]').textContent=`Last score: ${score}/${pool.length}`}start?.addEventListener('click',begin);el.querySelector('.quiz-next').addEventListener('click',next);begin();}
function initGames(){const root=document.getElementById('games-app');if(!root)return;const circuit=[['A 5 V source is connected to an LED. Which addition is normally needed in series with the LED?',['Current-limiting resistor','Second battery in parallel','A fuse rated 0 A','An antenna'],'Current-limiting resistor'],['A relay coil is switched off. What component is commonly placed across the DC coil?',['Flyback diode','LDR','Crystal','ADC'],'Flyback diode'],['A sensor output is 0–3.3 V but a 5 V-only input is expected. What should you check first?',['Logic-level compatibility','Wire color','Board logo','Screw size'],'Logic-level compatibility']];let n=0,pts=0;function show(){const q=circuit[n%circuit.length];root.querySelector('.game-question').textContent=q[0];root.querySelector('.game-options').innerHTML=q[1].sort(()=>Math.random()-.5).map((o,i)=>`<button class="game-option" data-v="${EG.esc(o)}">${String.fromCharCode(65+i)}. ${EG.esc(o)}</button>`).join('');root.querySelector('.game-feedback').textContent='';root.querySelectorAll('.game-option').forEach(b=>b.onclick=()=>{const ok=b.dataset.v===q[2];if(ok){pts++;EG.addXP(15)}else EG.addXP(2);root.querySelector('.game-feedback').textContent=ok?'⚡ Circuit fixed! +15 XP':'Try again: think about the electrical role of the component.';root.querySelectorAll('.game-option').forEach(x=>x.disabled=true);root.querySelector('.game-score').textContent=`Solved: ${pts}`})}root.querySelector('.game-next').onclick=()=>{n++;show()};show();}
function initTools(){const r=document.getElementById('tools-app');if(!r)return;const out=(id,v)=>r.querySelector('#'+id).textContent=v;function calc(){const v=Number(r.querySelector('#v').value),res=Number(r.querySelector('#r').value),i=Number(r.querySelector('#i').value);if(v&&res)out('ohm-result',`I = ${(v/res).toFixed(6).replace(/0+$/,'').replace(/\.$/,'')} A`);else if(v&&i)out('ohm-result',`R = ${(v/i).toFixed(4)} Ω`);else if(res&&i)out('ohm-result',`V = ${(res*i).toFixed(4)} V`);else out('ohm-result','Enter any two values.')}r.querySelector('#ohm-calc').onclick=calc;r.querySelector('#led-calc').onclick=()=>{const s=Number(r.querySelector('#led-v').value),f=Number(r.querySelector('#led-f').value),m=Number(r.querySelector('#led-i').value)/1000;out('led-result',m>0?`R ≈ ${((s-f)/m).toFixed(1)} Ω`:'Enter a valid LED current.')}r.querySelector('#divider-calc').onclick=()=>{const v=Number(r.querySelector('#div-v').value),r1=Number(r.querySelector('#div-r1').value),r2=Number(r.querySelector('#div-r2').value);out('divider-result',r1+r2?`Vout ≈ ${(v*r2/(r1+r2)).toFixed(3)} V`:'Enter valid resistances.')}r.querySelector('#binary-calc').onclick=()=>{const x=r.querySelector('#binary').value.trim();const n=parseInt(x,2);out('binary-result',Number.isNaN(n)?'Enter a binary number.':`${n} decimal = 0x${n.toString(16).toUpperCase()} hex`)};}
function init(){EG.paintStats();initQuiz();initGames();initTools();}document.addEventListener('DOMContentLoaded',init);
