(() => {
const app=document.getElementById('studio-app'); if(!app)return;
const projects=[
{id:'sevenseg',cat:'DIGITAL',name:'7-Segment Display',desc:'Design a reusable digital display interface with current limiting and a microcontroller driver.',mcu:'Arduino UNO / ESP32',power:'5 V',complexity:'Foundational',bom:[['7-segment display','1','Common-cathode or selected part','Display'],['Resistor','7','220 Ω typical','Segment current limiting'],['Microcontroller','1','Arduino UNO / ESP32','Control'],['Capacitor','1','100 nF','Local decoupling'],['Header','1','2.54 mm','Programming/interface']]},
{id:'divider',cat:'ANALOG',name:'Precision Voltage Divider',desc:'Build a controlled voltage node from a higher supply and verify the calculated output.',mcu:'None',power:'5–12 V',complexity:'Foundational',bom:[['Resistor R1','1','10 kΩ','Upper leg'],['Resistor R2','1','10 kΩ','Lower leg'],['Capacitor','1','100 nF','Filtering'],['Test point','1','TP','Measurement']]},
{id:'sensor',cat:'EMBEDDED',name:'ESP32 Sensor Node',desc:'Sensor acquisition platform with regulated power, decoupling and I²C expansion.',mcu:'ESP32',power:'5 V input / 3.3 V logic',complexity:'Intermediate',bom:[['ESP32 module','1','ESP32-WROOM class','Controller'],['Sensor','1','I²C sensor','Measurement'],['Capacitor','2','100 nF + 10 µF','Decoupling'],['Pull-up resistors','2','4.7 kΩ','I²C'],['USB connector','1','USB-C / Micro USB','Power/programming']]},
{id:'opamp',cat:'ANALOG',name:'Non-Inverting Op-Amp',desc:'A practical amplifier stage with feedback network, supply bypassing and test points.',mcu:'None',power:'5–12 V',complexity:'Intermediate',bom:[['Op-amp','1','LM358-class','Amplifier'],['Resistor','2','10 kΩ / 100 kΩ','Gain setting'],['Capacitor','1','100 nF','Supply bypass'],['Input connector','1','2-pin','Signal'],['Test point','2','TP','Measurement']]},
{id:'uart',cat:'COMMUNICATION',name:'UART Interface',desc:'Microcontroller serial interface with protection and connectorization.',mcu:'MCU dependent',power:'3.3 V / 5 V',complexity:'Intermediate',bom:[['MCU','1','Arduino / ESP32','Controller'],['Header','1','3–4 pin','UART'],['Resistor','2','1 kΩ','Protection/conditioning'],['TVS/protection','1','Logic-level suitable','ESD protection']]},
{id:'buck',cat:'POWER',name:'Regulated Buck Supply',desc:'A switching power stage for stepping down an input rail with protection and filtering.',mcu:'None',power:'12 V → 5 V',complexity:'Advanced',bom:[['Buck regulator','1','Selected IC/module','Conversion'],['Inductor','1','Rated for load current','Energy storage'],['Diodes/MOSFETs','as required','Per controller topology','Switching'],['Input/output capacitors','2+','Per datasheet','Filtering'],['Fuse','1','Rated for source','Protection']]}
];
let filter='ALL';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(){const q=(document.getElementById('studio-search-input')?.value||'').toLowerCase().trim();const list=projects.filter(p=>(filter==='ALL'||p.cat===filter)&&(!q||(p.name+' '+p.desc+' '+p.cat).toLowerCase().includes(q)));app.innerHTML='<div class="studio-layout"><aside class="studio-side"><h3>Project domains</h3>'+['ALL','ANALOG','DIGITAL','EMBEDDED','COMMUNICATION','POWER'].map(x=>'<button class="'+(filter===x?'active':'')+'" data-filter="'+x+'">'+x+'</button>').join('')+'<div class="studio-note">ElectroGuide is the project-planning layer. KiCad remains the engineering workspace for schematic capture, footprints, PCB layout and manufacturing outputs.</div></aside><section class="studio-main"><span class="studio-kicker">'+list.length+' project templates</span><h2>Engineering Project Library</h2><div class="studio-grid">'+list.map(p=>'<article class="studio-card" data-project="'+p.id+'"><h3>'+esc(p.name)+'</h3><p>'+esc(p.desc)+'</p><div class="studio-note"><b>'+esc(p.complexity)+'</b> · '+esc(p.power)+'</div></article>').join('')+'</div><div id="studio-detail"></div></section></div>';document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});document.querySelectorAll('[data-project]').forEach(c=>c.onclick=()=>openProject(c.dataset.project));}
function openProject(id){const p=projects.find(x=>x.id===id);if(!p)return;const d=document.getElementById('studio-detail');d.innerHTML='<div class="studio-detail"><span class="studio-kicker">Project specification</span><h2>'+esc(p.name)+'</h2><p>'+esc(p.desc)+'</p><div class="spec-grid"><div class="spec"><small>Controller</small><strong>'+esc(p.mcu)+'</strong></div><div class="spec"><small>Power</small><strong>'+esc(p.power)+'</strong></div><div class="spec"><small>Complexity</small><strong>'+esc(p.complexity)+'</strong></div></div><div class="workflow"><div class="active">01 Requirements</div><div class="active">02 BOM</div><div>03 Schematic</div><div>04 PCB</div><div>05 Manufacturing</div></div><h3>Bill of Materials</h3><table class="bom"><thead><tr><th>Item</th><th>Qty</th><th>Recommended</th><th>Purpose</th></tr></thead><tbody>'+p.bom.map(r=>'<tr>'+r.map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>').join('')+'</tbody></table><div class="studio-actions"><button class="studio-btn" id="generate-kicad">Prepare KiCad project</button><button class="studio-btn" id="export-bom" style="background:#fff;color:#244e6b">Export BOM</button></div><div class="studio-status" id="studio-status"></div><div class="studio-note"><b>KiCad handoff:</b> ElectroGuide defines requirements and the component set. Native KiCad project/schematic generation is the next integration layer; after handoff you continue with ERC, footprint assignment, PCB placement, routing and fabrication.</div></div>';document.getElementById('generate-kicad').onclick=()=>document.getElementById('studio-status').textContent='Project specification prepared. Native .kicad_pro/.kicad_sch generation will be attached in the KiCad integration stage.';document.getElementById('export-bom').onclick=()=>{const csv=['Item,Qty,Recommended,Purpose',...p.bom.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=p.id+'-BOM.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};d.scrollIntoView({behavior:'smooth',block:'start'});}
document.getElementById('studio-search-input').addEventListener('input',render);render();
})();