(() => {
  const canvas=document.getElementById('sim-canvas'),scope=document.getElementById('scope'),ctx=scope.getContext('2d'),list=document.getElementById('component-list');
  const state={parts:[],wires:[],selected:null,running:false,timer:null};
  const defs={
    battery:['Battery','🔋',['+','−'],9,'Power'],dc:['DC Voltage Source','🔌',['+','−'],5,'Power'],ac:['AC Voltage Source','〰️',['~','~'],230,'Power'],
    resistor:['Resistor','▭',['A','B'],330,'Passive'],capacitor:['Capacitor','▱',['+','−'],100,'Passive'],electrocap:['Electrolytic Capacitor','▱',['+','−'],100,'Passive'],inductor:['Inductor','🌀',['A','B'],10,'Passive'],pot:['Potentiometer','🎚️',['A','W','B'],500,'Passive'],thermistor:['Thermistor','🌡️',['A','B'],10000,'Passive'],ldr:['LDR','☀️',['A','B'],1000,'Passive'],varistor:['Varistor','⚡',['A','B'],10000,'Passive'],
    diode:['Diode','▶|',['A','K'],.7,'Diodes'],zener:['Zener Diode','◀|',['A','K'],5.1,'Diodes'],led:['LED','💡',['A','K'],2,'Diodes'],photodiode:['Photodiode','🔆',['A','K'],.7,'Diodes'],schottky:['Schottky Diode','▶|',['A','K'],.3,'Diodes'],bridge:['Bridge Rectifier','◇',['AC1','AC2','+','−'],0,'Diodes'],
    npn:['NPN Transistor','▥',['B','C','E'],0,'Transistors'],pnp:['PNP Transistor','▥',['B','C','E'],0,'Transistors'],nmos:['N-MOSFET','▥',['G','D','S'],0,'Transistors'],pmos:['P-MOSFET','▥',['G','D','S'],0,'Transistors'],jfet:['JFET','▥',['G','D','S'],0,'Transistors'],scr:['SCR','▥',['G','A','K'],0,'Semiconductors'],triac:['TRIAC','▥',['G','A1','A2'],0,'Semiconductors'],
    switch:['Switch','⏻',['A','B'],0,'Switches'],button:['Push Button','🔘',['A','B'],0,'Switches'],dip:['DIP Switch','🎛️',['A','B'],0,'Switches'],relay:['Relay','🔁',['Coil+','Coil−','COM','NO','NC'],0,'Switches'],fuse:['Fuse','🧯',['A','B'],1,'Protection'],
    crystal:['Crystal','💎',['A','B'],16,'Timing'],timer555:['555 Timer','🔲',['VCC','TRIG','OUT','GND'],0,'ICs'],opamp:['Op-Amp','🔺',['+','−','OUT','VCC','GND'],0,'ICs'],
    and:['AND Gate','∧',['A','B','Y','VCC','GND'],0,'Digital'],or:['OR Gate','∨',['A','B','Y','VCC','GND'],0,'Digital'],not:['NOT Gate','¬',['A','Y','VCC','GND'],0,'Digital'],xor:['XOR Gate','⊕',['A','B','Y','VCC','GND'],0,'Digital'],nand:['NAND Gate','⊼',['A','B','Y','VCC','GND'],0,'Digital'],nor:['NOR Gate','⊽',['A','B','Y','VCC','GND'],0,'Digital'],flipflop:['Flip-Flop','◫',['D','CLK','Q','Q̅','VCC','GND'],0,'Digital'],counter:['Counter IC','🔢',['CLK','RESET','Q','VCC','GND'],0,'Digital'],
    reg5:['5V Regulator','⚡',['IN','GND','OUT'],5,'Power'],reg12:['12V Regulator','⚡',['IN','GND','OUT'],12,'Power'],buck:['Buck Converter','⬇️',['IN+','IN−','OUT+','OUT−'],5,'Power'],boost:['Boost Converter','⬆️',['IN+','IN−','OUT+','OUT−'],12,'Power'],
    motor:['DC Motor','⚙️',['+','−'],0,'Output'],servo:['Servo Motor','🔧',['V+','GND','SIG'],90,'Output'],buzzer:['Buzzer','🔊',['+','−'],0,'Output'],speaker:['Speaker','🔈',['+','−'],0,'Output'],seven:['7-Segment Display','8️⃣',['VCC','A','B','C','D','E','F','G'],0,'Displays'],lcd:['16x2 LCD','📟',['VCC','GND','SDA','SCL'],0,'Displays'],rgb:['RGB LED','🌈',['R','G','B','K'],0,'Displays'],
    arduino:['Arduino UNO','🤖',['5V','GND','D2','D3','D4','A0'],0,'Microcontrollers'],esp32:['ESP32','📶',['3V3','GND','GPIO0','GPIO2','GPIO4','GPIO5'],0,'Microcontrollers'],
    ultrasonic:['Ultrasonic Sensor','📡',['VCC','GND','TRIG','ECHO'],0,'Sensors'],pir:['PIR Sensor','🚶',['VCC','GND','OUT'],0,'Sensors'],lm35:['LM35 Temperature Sensor','🌡️',['VCC','VOUT','GND'],0,'Sensors'],hall:['Hall Sensor','🧲',['VCC','GND','OUT'],0,'Sensors'],current:['Current Sensor','📊',['IN','OUT','VCC','GND'],0,'Sensors'],voltage:['Voltage Sensor','📈',['IN+','IN−','VCC','GND'],0,'Sensors'],
    osc:['Oscilloscope Probe','📈',['PROBE','GND'],0,'Test'],test:['Test Point','🔎',['TP'],0,'Test'],ground:['Ground','⏚',['GND'],0,'Connections'],vcc:['VCC Rail','🔴',['VCC'],5,'Connections'],terminal2:['2-Pin Terminal','🔩',['1','2'],0,'Connections'],terminal3:['3-Pin Terminal','🔩',['1','2','3'],0,'Connections']
  };
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const groups=[...new Set(Object.values(defs).map(d=>d[4]))];
  groups.forEach(g=>{const h=document.createElement('div');h.className='component-group-title';h.textContent=g;list.appendChild(h);Object.entries(defs).filter(([,d])=>d[4]===g).forEach(([id,d])=>{const b=document.createElement('button');b.className='component-btn';b.type='button';b.textContent=`${d[1]} ${d[0]}`;b.onclick=()=>addPart(id);list.appendChild(b);});});
  function addPart(type){const d=defs[type],i=state.parts.length;state.parts.push({id:`p${i}`,type,x:150+(i%4)*205,y:120+Math.floor(i/4)*125});render();status(`${d[0]} added. Click two yellow terminals to wire it.`);}
  function pinPos(p,n){const pins=defs[p.type][2],gap=38,i=pins.indexOf(n),start=p.x-(pins.length-1)*gap/2;return[start+i*gap,p.y+76];}
  function render(){canvas.innerHTML='<rect x="0" y="0" width="900" height="560" fill="#020a10"/>';state.wires.forEach(w=>{const a=state.parts.find(p=>p.id===w.a),b=state.parts.find(p=>p.id===w.b);if(a&&b){const A=pinPos(a,w.ap),B=pinPos(b,w.bp);canvas.insertAdjacentHTML('beforeend',`<line class="sim-wire" x1="${A[0]}" y1="${A[1]}" x2="${B[0]}" y2="${B[1]}"/>`);}});state.parts.forEach(p=>{const d=defs[p.type],w=Math.max(115,Math.min(190,d[2].length*38+40));canvas.insertAdjacentHTML('beforeend',`<g><rect class="sim-component" x="${p.x-w/2}" y="${p.y}" width="${w}" height="80" rx="12"/><text class="sim-label" x="${p.x}" y="${p.y+29}">${d[1]} ${esc(d[0])}</text><text class="sim-sub" x="${p.x}" y="${p.y+51}">${esc(d[4])}</text>${d[2].map((n,i)=>{const[x,y]=pinPos(p,n);return`<circle class="sim-terminal ${state.selected&&state.selected.pid===p.id&&state.selected.pin===n?'selected':''}" data-pid="${p.id}" data-pin="${esc(n)}" cx="${x}" cy="${y}" r="9"/><text class="sim-sub" x="${x}" y="${y+22}">${esc(n)}</text>`}).join('')}</g>`);});canvas.querySelectorAll('.sim-terminal').forEach(e=>e.onclick=x=>{x.stopPropagation();connect(e.dataset.pid,e.dataset.pin);});}
  function connect(pid,pin){if(!state.selected){state.selected={pid,pin};document.getElementById('selected-info').textContent=`Selected ${defs[state.parts.find(p=>p.id===pid).type][0]} — ${pin}. Now select another terminal.`;render();return;}if(state.selected.pid!==pid||state.selected.pin!==pin){const s=state.selected;const exists=state.wires.some(w=>(w.a===s.pid&&w.ap===s.pin&&w.b===pid&&w.bp===pin)||(w.b===s.pid&&w.bp===s.pin&&w.a===pid&&w.ap===pin));if(!exists)state.wires.push({a:s.pid,ap:s.pin,b:pid,bp:pin});}state.selected=null;document.getElementById('selected-info').textContent='Connection made. Select another pair of terminals.';render();checkReady();}
  function has(t){return state.parts.some(p=>p.type===t)}
  function complete(){const power=has('battery')||has('dc')||has('ac')||has('vcc');const useful=state.parts.filter(p=>!['ground','osc','test','vcc'].includes(p.type));return power&&useful.length>=1&&state.wires.length>=Math.max(1,useful.length-1)&&useful.every(p=>state.wires.some(w=>w.a===p.id||w.b===p.id));}
  function checkReady(){if(complete())status('✅ Circuit connected. Press Run Simulation to calculate it and show the oscilloscope waveform.','ok');}
  function status(t,k=''){const s=document.getElementById('sim-status');s.textContent=t;s.className='sim-status '+k;}
  function clearScope(){ctx.clearRect(0,0,scope.width,scope.height);ctx.strokeStyle='#24465b';ctx.lineWidth=1;for(let x=0;x<scope.width;x+=50){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,scope.height);ctx.stroke();}for(let y=0;y<scope.height;y+=35){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(scope.width,y);ctx.stroke();}}
  function drawWave(){clearScope();ctx.strokeStyle='#00ffc8';ctx.lineWidth=3;ctx.beginPath();const rc=has('capacitor')||has('electrocap'),digital=['and','or','not','xor','nand','nor','flipflop','counter'].some(has),ac=has('ac')||has('timer555')||has('crystal');for(let x=0;x<scope.width;x++){let y=140;if(rc)y=235-175*(1-Math.exp(-(x/150)/1.1));else if(digital)y=x%100<50?65:215;else if(ac)y=140+70*Math.sin(x/18);else if(has('led'))y=140+45*Math.sin(x/20);else y=140+55*Math.sin(x/28);x?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.stroke();document.getElementById('scope-readout').textContent=rc?'RC charging transient':digital?'Digital switching waveform':ac?'AC / clock waveform':has('led')?'LED circuit waveform':'Circuit signal waveform';}
  function run(){if(!complete()){status('⚠ Complete the circuit first: add a power source and components, then connect their terminals.','warn');return;}state.running=true;document.getElementById('live-badge').textContent='● RUNNING';const V=has('ac')?230:has('vcc')?5:has('dc')?5:9,R=state.parts.find(p=>p.type==='resistor')?.value||330,I=has('led')?Math.max(0,(V-2)/R*1000):has('resistor')?V/R*1000:0;document.getElementById('meter-v').textContent=V.toFixed(2)+' V';document.getElementById('meter-i').textContent=I.toFixed(2)+' mA';document.getElementById('meter-p').textContent=(V*I).toFixed(2)+' mW';status('✅ Simulation running. Oscilloscope waveform is live.','ok');drawWave();if(state.timer)clearInterval(state.timer);state.timer=setInterval(drawWave,700);}
  function reset(){state.parts=[];state.wires=[];state.selected=null;state.running=false;if(state.timer)clearInterval(state.timer);document.getElementById('live-badge').textContent='● STOPPED';document.getElementById('meter-v').textContent='0 V';document.getElementById('meter-i').textContent='0 mA';document.getElementById('meter-p').textContent='0 mW';document.getElementById('selected-info').textContent='No terminal selected.';status('Add components from the library to begin.');clearScope();render();}
  document.getElementById('simulate').onclick=run;document.getElementById('reset-sim').onclick=reset;document.getElementById('clear-sim').onclick=reset;clearScope();render();
})();