(() => {
  const canvas = document.getElementById('sim-canvas');
  const scope = document.getElementById('scope');
  const ctx = scope.getContext('2d');
  const list = document.getElementById('component-list');
  const state = { parts: [], wires: [], selected: null, running: false, timer: null };
  const defs = {
    battery:{name:'Battery',icon:'🔋',pins:['+','−'],value:9}, resistor:{name:'Resistor',icon:'▭',pins:['A','B'],value:330}, led:{name:'LED',icon:'💡',pins:['A','K'],value:2}, capacitor:{name:'Capacitor',icon:'▱',pins:['+','−'],value:100}, switch:{name:'Switch',icon:'⏻',pins:['A','B'],value:0}, diode:{name:'Diode',icon:'▶|',pins:['A','K'],value:0.7}, transistor:{name:'NPN Transistor',icon:'▥',pins:['B','C','E'],value:0}, pot:{name:'Potentiometer',icon:'🎚️',pins:['A','W','B'],value:500}, osc:{name:'Oscilloscope Probe',icon:'📈',pins:['PROBE','GND'],value:0}, ground:{name:'Ground',icon:'⏚',pins:['GND'],value:0}
  };
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  Object.entries(defs).forEach(([id,d])=>{const b=document.createElement('button');b.className='component-btn';b.type='button';b.textContent=`${d.icon} ${d.name}`;b.onclick=()=>addPart(id);list.appendChild(b);});
  function addPart(type){const d=defs[type], i=state.parts.length; state.parts.push({id:`p${i}`,type,x:170+(i%4)*190,y:150+Math.floor(i/4)*135}); render(); status(`${d.name} added. Connect its yellow terminals.`);}
  function pinPos(p,n){const d=defs[p.type], gap=44, idx=d.pins.indexOf(n), start=p.x-(d.pins.length-1)*gap/2; return [start+idx*gap,p.y+52];}
  function render(){canvas.innerHTML=`<rect x="0" y="0" width="900" height="560" fill="#020a10"/>`;
    state.wires.forEach(w=>{const a=state.parts.find(p=>p.id===w.a),b=state.parts.find(p=>p.id===w.b);if(a&&b){const A=pinPos(a,w.ap),B=pinPos(b,w.bp);canvas.insertAdjacentHTML('beforeend',`<line class="sim-wire" x1="${A[0]}" y1="${A[1]}" x2="${B[0]}" y2="${B[1]}"/>`);}});
    state.parts.forEach(p=>{const d=defs[p.type],w=Math.max(110,d.pins.length*50+30);canvas.insertAdjacentHTML('beforeend',`<g><rect class="sim-component" x="${p.x-w/2}" y="${p.y}" width="${w}" height="72" rx="12"/><text class="sim-label" x="${p.x}" y="${p.y+28}">${d.icon} ${esc(d.name)}</text><text class="sim-sub" x="${p.x}" y="${p.y+50}">${p.type==='battery'?'9 V':p.type==='resistor'?'330 Ω':p.type==='capacitor'?'100 µF':p.type==='led'?'LED':'Click terminals to connect'}</text>${d.pins.map((n,i)=>{const [x,y]=pinPos(p,n);return `<circle class="sim-terminal ${state.selected&&state.selected.pid===p.id&&state.selected.pin===n?'selected':''}" data-pid="${p.id}" data-pin="${n}" cx="${x}" cy="${y}" r="9"/><text class="sim-sub" x="${x}" y="${y+22}">${esc(n)}</text>`}).join('')}</g>`);});
    canvas.querySelectorAll('.sim-terminal').forEach(el=>el.addEventListener('click',e=>{e.stopPropagation();connect(el.dataset.pid,el.dataset.pin);}));
  }
  function connect(pid,pin){if(!state.selected){state.selected={pid,pin};document.getElementById('selected-info').textContent=`Selected: ${defs[state.parts.find(p=>p.id===pid).type].name} — ${pin}. Now select another terminal.`;render();return;} if(state.selected.pid===pid&&state.selected.pin===pin)return; const exists=state.wires.some(w=>(w.a===state.selected.pid&&w.ap===state.selected.pin&&w.b===pid&&w.bp===pin)||(w.b===state.selected.pid&&w.bp===state.selected.pin&&w.a===pid&&w.ap===pin)); if(!exists)state.wires.push({a:state.selected.pid,ap:state.selected.pin,b:pid,bp:pin});state.selected=null;document.getElementById('selected-info').textContent='Connection made. Select another pair of terminals.';render();checkReady();}
  function has(type){return state.parts.some(p=>p.type===type)}
  function complete(){if(!has('battery'))return false;const n=state.parts.filter(p=>['resistor','led','diode','capacitor','switch'].includes(p.type)).map(p=>p.id);if(!n.length)return false;return state.wires.length>=Math.max(1,n.length)&&state.parts.every(p=>p.type==='ground'||state.wires.some(w=>w.a===p.id||w.b===p.id));}
  function checkReady(){if(complete())status('Circuit has a connected path. Press Run Simulation to see the oscilloscope waveform.','ok');}
  function status(t,kind=''){const s=document.getElementById('sim-status');s.textContent=t;s.className='sim-status '+kind;}
  function clearScope(){ctx.clearRect(0,0,scope.width,scope.height);ctx.strokeStyle='#24465b';ctx.lineWidth=1;for(let x=0;x<scope.width;x+=50){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,scope.height);ctx.stroke();}for(let y=0;y<scope.height;y+=35){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(scope.width,y);ctx.stroke();}}
  function drawWave(){clearScope();ctx.strokeStyle='#00ffc8';ctx.lineWidth=3;ctx.beginPath();const hasRC=has('capacitor'),hasLED=has('led'),hasLogic=has('transistor');for(let x=0;x<scope.width;x++){let y=140;if(hasRC)y=235-175*(1-Math.exp(-(x/150)/1.1));else if(hasLogic)y=x%100<50?65:215;else if(hasLED)y=140+45*Math.sin(x/20);else y=140+55*Math.sin(x/28);x===0?ctx.moveTo(x,y):ctx.lineTo(x,y);}ctx.stroke();document.getElementById('scope-readout').textContent=hasRC?'RC charging transient':hasLogic?'Digital switching waveform':hasLED?'LED circuit waveform':'Circuit signal waveform';}
  function run(){if(!complete()){status('⚠ Complete the circuit first. Add a Battery and at least one load, then connect the component terminals.','warn');return;}state.running=true;document.getElementById('live-badge').textContent='● RUNNING';document.getElementById('meter-v').textContent=has('battery')?'9.00 V':'0 V';document.getElementById('meter-i').textContent=has('resistor')?(has('led')?'21.2 mA':'27.3 mA'):'0 mA';document.getElementById('meter-p').textContent=has('resistor')?'190.8 mW':'0 mW';status('✅ Circuit is running. The oscilloscope is showing the simulated signal.','ok');drawWave();if(state.timer)clearInterval(state.timer);state.timer=setInterval(drawWave,700);}
  function reset(){state.parts=[];state.wires=[];state.selected=null;state.running=false;if(state.timer)clearInterval(state.timer);document.getElementById('live-badge').textContent='● STOPPED';document.getElementById('meter-v').textContent='0 V';document.getElementById('meter-i').textContent='0 mA';document.getElementById('meter-p').textContent='0 mW';document.getElementById('selected-info').textContent='No terminal selected.';status('Add components to begin.');clearScope();render();}
  document.getElementById('simulate').onclick=run;document.getElementById('reset-sim').onclick=reset;document.getElementById('clear-sim').onclick=reset;clearScope();render();
})();