(()=>{
const $=id=>document.getElementById(id);const out=(id,t)=>{const e=$(id);if(e)e.innerHTML=t};
const tools=[
['calc',"Ohm's Law",'Calculate V, I, R and power','V=I×R'],['calc','Power Calculator','Voltage, current, resistance and power','P=VI'],['calc','Voltage Divider','Find output voltage','Vout=Vin×R2/(R1+R2)'],['calc','Current Divider','Find branch current','I1=It×R2/(R1+R2)'],['calc','LED Resistor','Choose safe LED resistor','R=(Vs−Vf)/I'],['calc','Series Resistors','Equivalent resistance','Req=R1+R2+…'],['calc','Parallel Resistors','Equivalent resistance','1/Req=Σ1/R'],['calc','Series Capacitors','Equivalent capacitance','1/Ceq=Σ1/C'],['calc','Parallel Capacitors','Equivalent capacitance','Ceq=ΣC'],['calc','RC Time Constant','Charging/discharging timing','τ=RC'],['calc','Frequency / Period','Convert frequency and period','T=1/f'],['calc','Angular Frequency','Find ω','ω=2πf'],['calc','dB Power Gain','Power ratio to dB','10log10(P2/P1)'],['calc','dB Voltage Gain','Voltage ratio to dB','20log10(V2/V1)'],['calc','Transformer Ratio','Turns, voltage and current','Vp/Vs=Np/Ns'],['calc','Battery Runtime','Estimate operating time','hours=Ah/A'],['calc','Energy / Wh','Battery energy','Wh=V×Ah'],['calc','Watt to Horsepower','Convert power','1 hp≈746 W'],['calc','Frequency to Wavelength','EM wavelength','λ=c/f'],['calc','Duty Cycle','Pulse duty cycle','D=Ton/T'],
['decoder','Resistor Color Code','Decode 4-band resistor','Colors → Ω'],['decoder','Capacitor Code','Decode 3-digit marking','104 → 100 nF'],['decoder','SMD Resistor Code','Decode 3/4 digit SMD values','103 → 10 kΩ'],['decoder','SMD Capacitor Code','Estimate common SMD marking','Code → pF'],['decoder','Diode Marking Guide','Identify common diode families','Part → use'],['decoder','Logic IC Pin Guide','Quick pin/function reference','IC → pins'],
['measure','Virtual Multimeter','Practice V, A, Ω and continuity','Measure safely'],['measure','Diode Test','Forward/reverse diode test','Vf + OPEN'],['measure','Continuity Tester','Check a virtual connection','BEEP / OPEN'],['measure','Component Tester','Test resistor, LED, diode, capacitor','PASS / CHECK'],['measure','Power Supply','Set voltage/current limit','Bench supply'],['measure','Battery Lab','Series/parallel battery setup','Pack voltage'],
['signal','Signal Generator','Create live sine/square/triangle/sawtooth signals','f, amplitude, offset'],['signal','Oscilloscope','View and measure waveforms','Vpp, RMS, T'],['signal','Logic Analyzer','Inspect digital channels','HIGH / LOW'],['signal','PWM Generator','Set frequency and duty cycle','PWM'],['signal','RC Waveform Lab','See capacitor charging','1−e^(−t/RC)'],['signal','Filter Response','Estimate RC low/high pass','fc=1/(2πRC)'],
['sensor','LDR Sensor Lab','Change light and observe resistance','Light → Ω'],['sensor','Thermistor Lab','Change temperature and resistance','Temp → Ω'],['sensor','LM35 Lab','Temperature to voltage','10 mV/°C'],['sensor','Ultrasonic Lab','Distance to echo time','t=2d/c'],['sensor','PIR Lab','Motion sensor output','LOW / HIGH'],['sensor','Hall Sensor Lab','Magnetic field switching','Field → output'],
['digital','Logic Gate Lab','AND/OR/NOT/XOR/NAND/NOR','Inputs → Y'],['digital','Binary / Decimal','Convert number systems','BIN ↔ DEC'],['digital','Hex / Binary','Convert hexadecimal','HEX ↔ BIN'],['digital',"Two's Complement",'Signed binary helper','N-bit'],['digital','Truth Table Builder','Generate gate truth table','Inputs → table'],
['diagnose','Circuit Troubleshooter','Find common wiring faults','Diagnose → fix'],['diagnose','Voltage Drop Checker','Check expected drops','ΣV=0'],['diagnose','Power Budget Checker','Check load vs supply','Margin'],['diagnose','Safety Checker','Flag risky circuit conditions','SAFE / WARNING'],['diagnose','Component Selection Helper','Choose a suitable basic part','Requirement → choice']
];
const host=$('tools-app'),search=$('tool-search'),cat=$('tool-category');const names={calc:'Calculators',decoder:'Decoders & References',measure:'Meters & Bench',signal:'Signals & Waveforms',sensor:'Sensor Labs',digital:'Digital & Logic',diagnose:'Diagnosis & Design'};
if(cat)cat.innerHTML='<option value="all">All tools (50)</option>'+Object.keys(names).map(c=>`<option value="${c}">${names[c]}</option>`).join('');
function fields(i){let a={calc:['Value A','Value B','Value C'],measure:['Voltage (V)','Resistance (Ω)'],signal:['Frequency (Hz)','Amplitude / Vpp (V)','Offset (V)'],sensor:['Input value'],digital:['Input A','Input B'],diagnose:['Supply (V)','Load current (A)'],decoder:['Code / value']}[tools[i][0]]||['Value'];return a.map((x,j)=>`<label>${x}<input id="t${i}-${j}" type="number" step="any" placeholder="${j?'':'Enter value'}"></label>`).join('')}
function signalCanvas(i){return `<div class="wave-controls"><label>Waveform<select id="wave-type-${i}"><option value="sine">Sine</option><option value="square">Square</option><option value="triangle">Triangle</option><option value="sawtooth">Sawtooth</option></select></label></div><div class="wave-wrap" style="margin-top:10px;border:1px solid rgba(0,255,200,.25);border-radius:10px;background:#02080c;padding:8px"><canvas id="wave${i}" width="700" height="240" style="width:100%;height:240px;display:block"></canvas><div id="waveinfo${i}" style="padding:8px;font-size:12px">Enter values and press Run Tool.</div></div>`}
function card(i,t){return `<article class="tool-card lab-tool" data-cat="${t[0]}" data-name="${t[1].toLowerCase()}"><div class="tool-tag">${names[t[0]]}</div><h2>${t[1]}</h2><p>${t[2]}</p><div class="formula">${t[3]}</div><div class="tool-inputs">${fields(i)}</div>${t[0]==='signal'?signalCanvas(i):''}<button class="primary-btn" data-run="${i}">Run Tool</button><output id="to${i}">Ready.</output><details><summary>How to use</summary><p>Enter the required values and press <b>Run Tool</b>. Signal tools show a live waveform directly on this card. For the Signal Generator use frequency in Hz, amplitude/Vpp in volts and offset in volts.</p></details></article>`}
function render(){let q=(search?.value||'').toLowerCase(),c=cat?.value||'all';host.innerHTML=tools.map((t,i)=>card(i,t)).filter((_,i)=>{let t=tools[i];return(c==='all'||t[0]===c)&&(!q||t[1].toLowerCase().includes(q)||t[2].toLowerCase().includes(q))}).join('');host.querySelectorAll('[data-run]').forEach(b=>b.onclick=()=>run(+b.dataset.run))}
function val(i,j){return parseFloat($(`t${i}-${j}`)?.value)}
function drawWave(i,type,freq,amp,offset,duty=50){const cv=$(`wave${i}`);if(!cv)return;const ctx=cv.getContext('2d'),w=cv.width,h=cv.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#02080c';ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(120,180,190,.25)';ctx.lineWidth=1;for(let x=0;x<=w;x+=70){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<=h;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.strokeStyle='#35e6c0';ctx.lineWidth=3;ctx.beginPath();let cycles=3;for(let x=0;x<=w;x++){let phase=(x/w)*cycles*2*Math.PI,yy;if(type==='square')yy=Math.sin(phase)>=0?1:-1;else if(type==='triangle')yy=2/Math.PI*Math.asin(Math.sin(phase));else if(type==='sawtooth')yy=2*((phase/(2*Math.PI))-Math.floor(phase/(2*Math.PI)+.5));else if(type==='pwm')yy=((phase/(2*Math.PI))%1)<duty/100?1:-1;else yy=Math.sin(phase);let py=h/2-(offset+yy*(amp||1))*h/5;x?ctx.lineTo(x,py):ctx.moveTo(x,py)}ctx.stroke();ctx.fillStyle='#dff';ctx.font='14px Arial';ctx.fillText(`${type.toUpperCase()}   ${freq} Hz   amplitude ${amp} V   offset ${offset} V`,12,22)}
function run(i){let t=tools[i],a=val(i,0),b=val(i,1),c=val(i,2),name=t[1],type=t[0],r='Enter the required values.';
if(name==="Ohm's Law")r=Number.isFinite(a)&&Number.isFinite(b)?`V=${(a*b).toFixed(3)} V • I=${a} A • R=${b} Ω • P=${(a*a*b).toFixed(3)} W`:'Enter I and R.';
else if(name==='Power Calculator')r=Number.isFinite(a)&&Number.isFinite(b)?`Power = <b>${(a*b).toFixed(3)} W</b>`:'Enter voltage and current.';
else if(name==='Voltage Divider')r=Number.isFinite(a)&&Number.isFinite(b)&&Number.isFinite(c)?`Vout = <b>${(a*c/(b+c)).toFixed(3)} V</b>`:'Enter Vin, R1, R2.';
else if(name==='Current Divider')r=Number.isFinite(a)&&Number.isFinite(b)&&Number.isFinite(c)?`Branch current = <b>${(a*c/(b+c)).toFixed(4)} A</b>`:'Enter total current and two resistors.';
else if(name==='LED Resistor')r=Number.isFinite(a)&&Number.isFinite(b)&&Number.isFinite(c)?`Recommended R ≈ <b>${Math.max(1,Math.ceil((a-b)/(c/1000)/10)*10)} Ω</b>`:'Enter supply, Vf and current.';
else if(name==='Series Resistors')r=`Req = <b>${[a,b,c].filter(Number.isFinite).reduce((x,y)=>x+y,0)} Ω</b>`;
else if(name==='Parallel Resistors'){let x=[a,b,c].filter(Number.isFinite);r=x.length?`Req ≈ <b>${(1/x.reduce((s,y)=>s+1/y,0)).toFixed(3)} Ω</b>`:'Enter resistors.'}
else if(name==='Series Capacitors'){let x=[a,b,c].filter(Number.isFinite);r=x.length?`Ceq ≈ <b>${(1/x.reduce((s,y)=>s+1/y,0)).toFixed(3)} µF</b>`:'Enter capacitors.'}
else if(name==='Parallel Capacitors')r=`Ceq ≈ <b>${[a,b,c].filter(Number.isFinite).reduce((x,y)=>x+y,0).toFixed(3)} µF</b>`;
else if(name==='RC Time Constant')r=Number.isFinite(a)&&Number.isFinite(b)?`τ = <b>${(a*b/1e6).toFixed(6)} s</b> (R Ω, C µF)`:'Enter R and C.';
else if(name==='Frequency / Period')r=Number.isFinite(a)&&a>0?`T = <b>${(1/a).toExponential(4)} s</b>`:'Enter frequency.';
else if(name==='Angular Frequency')r=Number.isFinite(a)?`ω = <b>${(2*Math.PI*a).toFixed(3)} rad/s</b>`:'Enter frequency.';
else if(name.includes('dB'))r=Number.isFinite(a)&&Number.isFinite(b)?`Gain = <b>${((name.includes('Power')?10:20)*Math.log10(b/a)).toFixed(3)} dB</b>`:'Enter two values.';
else if(name==='Battery Runtime')r=Number.isFinite(a)&&Number.isFinite(b)?`Estimated runtime = <b>${(a/b).toFixed(2)} h</b>`:'Enter Ah and load A.';
else if(name==='Energy / Wh')r=Number.isFinite(a)&&Number.isFinite(b)?`Energy = <b>${(a*b).toFixed(2)} Wh</b>`:'Enter V and Ah.';
else if(name==='Watt to Horsepower')r=Number.isFinite(a)?`≈ <b>${(a/746).toFixed(3)} hp</b>`:'Enter watts.';
else if(name==='Frequency to Wavelength')r=Number.isFinite(a)&&a>0?`λ ≈ <b>${(299792458/a).toFixed(3)} m</b>`:'Enter Hz.';
else if(name==='Duty Cycle')r=Number.isFinite(a)&&Number.isFinite(b)&&b>0?`Duty cycle = <b>${(a/b*100).toFixed(2)}%</b>`:'Enter Ton and period.';
else if(type==='signal'){let f=Number.isFinite(a)&&a>0?a:1000,amp=Number.isFinite(b)?b:1,off=Number.isFinite(c)?c:0,mode=$(`wave-type-${i}`)?.value||'sine',duty=Math.max(0,Math.min(100,b||50));if(name==='PWM Generator')drawWave(i,'pwm',f,1,0,duty);else drawWave(i,mode,f,amp,off);r=`Waveform displayed: <b>${name==='PWM Generator'?'PWM':mode}</b> • ${f} Hz • ${amp} V amplitude • ${off} V offset.`;let info=$(`waveinfo${i}`);if(info)info.innerHTML=`✓ Live waveform is running. Change the values/waveform and press Run Tool again.`}
else if(type==='decoder')r=`<b>${String($(`t${i}-0`)?.value||'').trim()||'Enter a code'}</b> → verify the part datasheet for the exact value.`;
else if(name==='Binary / Decimal'){let s=$(`t${i}-0`)?.value||'';r=/^[01]+$/.test(s)?`Decimal = <b>${parseInt(s,2)}</b>`:'Enter binary digits only.'}
else if(name==='Hex / Binary'){let s=$(`t${i}-0`)?.value||'';r=/^[0-9a-f]+$/i.test(s)?`Binary = <b>${parseInt(s,16).toString(2).padStart(4,'0')}</b>`:'Enter hexadecimal digits.'}
else if(name==='Ultrasonic Lab'&&Number.isFinite(a))r=`Echo time ≈ <b>${(2*a/343*1000).toFixed(3)} ms</b>`;
else if(name==='LM35 Lab'&&Number.isFinite(a))r=`Output ≈ <b>${(a*0.01).toFixed(3)} V</b>`;
else if(name==='LDR Sensor Lab'&&Number.isFinite(a))r='Higher light level generally means <b>lower resistance</b> for an LDR.';
else if(name==='RC Waveform Lab')r='Charging: 0% → 63% at τ → 95% at 3τ → 99% at 5τ.';
else if(name==='Filter Response'&&Number.isFinite(a)&&Number.isFinite(b)&&a>0&&b>0)r=`Cutoff frequency fc ≈ <b>${(1/(2*Math.PI*a*b)).toFixed(3)} Hz</b>`;
else if(name==='Logic Gate Lab'){let A=a!==0,B=b!==0;r=`AND=${A&&B?1:0} • OR=${A||B?1:0} • XOR=${A!==B?1:0} • NAND=${!(A&&B)?1:0} • NOR=${!(A||B)?1:0}`}
else if(type==='measure')r='Virtual bench ready. Choose the correct measurement mode before connecting probes.';
else if(type==='diagnose')r='Check supply polarity → ground → continuity → component orientation → current limit.';
out('to'+i,r)}
if(search)search.oninput=render;if(cat)cat.onchange=render;render();
})();