(()=>{
'use strict';
const $=id=>document.getElementById(id);
const val=id=>parseFloat($(id)?.value);
const show=(id,text)=>{const e=$(id);if(e)e.innerHTML=text};

function wire(id,fn){const e=$(id);if(e)e.addEventListener('click',fn)}

wire('ohm-calc',()=>{
 const V=val('v'),R=val('r'),I=val('i');
 if(Number.isFinite(V)&&Number.isFinite(R)&&R!==0){const i=V/R;show('ohm-result',`Current = <b>${i.toFixed(4)} A</b> • Power = <b>${(V*i).toFixed(3)} W</b>`);return}
 if(Number.isFinite(V)&&Number.isFinite(I)&&I!==0){const r=V/I;show('ohm-result',`Resistance = <b>${r.toFixed(3)} Ω</b> • Power = <b>${(V*I).toFixed(3)} W</b>`);return}
 if(Number.isFinite(I)&&Number.isFinite(R)){const v=I*R;show('ohm-result',`Voltage = <b>${v.toFixed(3)} V</b> • Power = <b>${(I*I*R).toFixed(3)} W</b>`);return}
 show('ohm-result','Enter any two values.');
});
wire('led-calc',()=>{const V=val('led-v'),Vf=val('led-f'),mA=val('led-i');if(V>Vf&&mA>0)show('led-result',`Resistor ≈ <b>${Math.ceil(((V-Vf)/(mA/1000))/10)*10} Ω</b> • Power ≈ <b>${(((V-Vf)*(mA/1000))).toFixed(3)} W</b>`);else show('led-result','Check supply, LED Vf and current.');});
wire('divider-calc',()=>{const V=val('div-v'),R1=val('div-r1'),R2=val('div-r2');if(V>=0&&R1>=0&&R2>0)show('divider-result',`Vout = <b>${(V*R2/(R1+R2)).toFixed(4)} V</b>`);else show('divider-result','Enter valid Vin, R1 and R2.');});
wire('rc-calc',()=>{const R=val('rc-r'),C=val('rc-c');if(R>0&&C>0)show('rc-result',`τ = <b>${(R*C/1000).toFixed(4)} s</b> • 63% charge ≈ <b>${(R*C/1000).toFixed(4)} s</b>`);else show('rc-result','Enter positive R and C.');});
wire('freq-calc',()=>{const f=val('freq-f');if(f>0)show('freq-result',`Period T = <b>${(1/f).toExponential(4)} s</b> • ${(1/f*1000).toFixed(4)} ms`);else show('freq-result','Enter frequency greater than 0 Hz.');});
wire('db-calc',()=>{const p=val('db-p');if(p>0)show('db-result',`Gain = <b>${(10*Math.log10(p)).toFixed(3)} dB</b>`);else show('db-result','Enter a positive power ratio.');});
const digit={black:0,brown:1,red:2,orange:3,yellow:4,green:5,blue:6,violet:7,gray:8,white:9};
wire('res-calc',()=>{const a=digit[$('c1')?.value],b=digit[$('c2')?.value],m=digit[$('c3')?.value],tol=$('c4')?.value;if(a!=null&&b!=null&&m!=null)show('res-result',`Resistance = <b>${(a*10+b)*Math.pow(10,m)} Ω</b> • Tolerance: <b>±${tol==='gold'?5:tol==='silver'?10:tol==='red'?2:1}%</b>`);});
wire('cap-calc',()=>{const s=String($('cap-code')?.value||'').trim();if(/^\d{3}$/.test(s)){const p=Number(s.slice(0,2))*Math.pow(10,Number(s[2]));show('cap-result',`Capacitance = <b>${p} pF</b> = <b>${(p/1000).toFixed(3)} nF</b>`)}else show('cap-result','Enter a 3-digit capacitor code, e.g. 104.');});
wire('bat-calc',()=>{const cap=val('bat-cap'),load=val('bat-load');if(cap>0&&load>0)show('bat-result',`Estimated runtime = <b>${(cap/load).toFixed(2)} hours</b>`);else show('bat-result','Enter capacity and load current.');});
wire('meter-calc',()=>{const mode=$('meter-mode')?.value,V=val('mv'),R=val('mr');if(mode==='V')show('meter-result',`Meter reading = <b>${Number.isFinite(V)?V:'—'} V</b>`);else if(mode==='Ω')show('meter-result',`Meter reading = <b>${Number.isFinite(R)?R:'—'} Ω</b>`);else if(mode==='A')show('meter-result',`For this practice meter, use I = V/R = <b>${Number.isFinite(V)&&R>0?(V/R).toFixed(4):'—'} A</b>`);else show('meter-result',R<50?'🔊 <b>BEEP — continuity</b>':'🔇 <b>OPEN</b>');});
wire('tester-calc',()=>{const t=$('test-type')?.value;const msg={res:'PASS — resistor should show a stable resistance.',led:'CHECK — forward direction should show LED conduction.',diode:'CHECK — forward conduction and reverse blocking expected.',cap:'CHARGE/DISCHARGE — capacitance should not behave like a permanent short.',npn:'CHECK — base controls collector/emitter conduction.',mos:'CHECK — gate controls drain/source conduction.'};show('test-result',msg[t]||'Test complete.');});
wire('fault-calc',()=>{const f=$('fault')?.value;const msg={led:'Reverse the LED: anode to positive, cathode toward the resistor/ground path.',open:'Trace continuity node-by-node until the open connection is found.',short:'Disconnect power immediately and check for a direct supply-to-ground path.',ground:'Connect the circuit ground/common reference before measuring signals.'};show('fault-result',msg[f]);});

function drawScope(){const cv=$('lab-scope');if(!cv)return;const ctx=cv.getContext('2d'),w=cv.width,h=cv.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#02080c';ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(120,180,190,.25)';ctx.lineWidth=1;for(let x=0;x<=w;x+=50){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<=h;y+=35){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}const f=val('sg-f')>0?val('sg-f'):1000,a=Number.isFinite(val('sg-a'))?val('sg-a'):2,o=Number.isFinite(val('sg-off'))?val('sg-off'):0,type=$('sg-wave')?.value||'sine';ctx.strokeStyle='#35e6c0';ctx.lineWidth=3;ctx.beginPath();for(let x=0;x<=w;x++){const ph=x/w*6*Math.PI;let y;if(type==='square')y=Math.sin(ph)>=0?1:-1;else if(type==='triangle')y=2/Math.PI*Math.asin(Math.sin(ph));else y=Math.sin(ph);const py=h/2-(o+y*a)*h/6;x?ctx.lineTo(x,py):ctx.moveTo(x,py)}ctx.stroke();ctx.fillStyle='#fff';ctx.font='15px Arial';ctx.fillText(`${type.toUpperCase()} • ${f} Hz • ${a} V amplitude • ${o} V offset`,12,22)}
wire('signal-calc',()=>{const f=val('sg-f'),a=val('sg-a'),o=val('sg-off');if(f>0&&Number.isFinite(a)){drawScope();show('sg-result',`✓ Waveform generated: <b>${$('sg-wave')?.value}</b> • ${f} Hz • ${a} V amplitude • ${Number.isFinite(o)?o:0} V offset`)}else show('sg-result','Enter a positive frequency and amplitude.');});
wire('sensor-calc',()=>{const t=$('sensor-type')?.value,x=val('sensor-value');if(!Number.isFinite(x)){show('sensor-result','Enter a value.');return}if(t==='ldr')show('sensor-result',`Light level = <b>${x}</b> → LDR resistance generally <b>decreases</b> as light increases.`);else if(t==='therm')show('sensor-result',`Temperature = <b>${x} °C</b> → thermistor resistance changes with temperature; use its datasheet curve for exact value.`);else show('sensor-result',`Temperature = <b>${x} °C</b> → LM35 output ≈ <b>${(x*0.01).toFixed(3)} V</b>`);});
wire('logic-calc',()=>{const A=$('la')?.checked?1:0,B=$('lb')?.checked?1:0,g=$('lg')?.value;let y;if(g==='AND')y=A&B;else if(g==='OR')y=A|B;else if(g==='NOT')y=A?0:1;else if(g==='XOR')y=A^B;else y=Number(!(A&B));show('logic-result',`A=${A} • B=${B} • <b>${g} output = ${y}</b>`);});
})();